services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
